name: Bug report
description: Report a reproducible defect in Neural OS
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide exact steps.
      placeholder: |
        1. Open ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS and version
      placeholder: macOS 15.1
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App version or commit
      placeholder: v0.1.0 or commit hash

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste logs and attach screenshots where possible.
